require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.harpoon")
require("core.plugin_config.completions")
require("core.plugin_config.mason")
require("core.plugin_config.gitsigns")
require("core.plugin_config.neogit")
require("core.plugin_config.colorscheme")
require("core.plugin_config.lsp_config")
require("core.plugin_config.glslview")
require("core.plugin_config.clangd_extensions")
require("core.plugin_config.rustaceanvim")
require("core.plugin_config.dap")
require("core.plugin_config.lualine")
require("core.plugin_config.web_devicons")

